<?php

namespace RCMPropuestasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PropuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropuestaRepository extends EntityRepository
{
}
