rcm_visitante_info:
    path: /info
    defaults: { _controller: RCMPropuestasBundle:Visitante:info }

rcm_visitante_contacto:
    path: /contacto
    defaults: { _controller: RCMPropuestasBundle:Visitante:contacto }

rcm_visitante_email:
    path: /email
    defaults: { _controller: RCMPropuestasBundle:Visitante:enviarEmail }
    methods: POST
